# Generated by Django 3.0.3 on 2020-08-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRecordd',
            new_name='AccessRecord',
        ),
    ]
